### ISSUE TITLE
Create custom rm anova function

### ISSUE THREAD

**Issue by lvjustice** [mark-andrews/psyntur#19]
To replace `ezANOVA()`

**Comment by mark-andrews** [comment]
But replace with what?
Googling a bit, I've come across this, 
https://www.datanovia.com/en/lessons/mixed-anova-in-r/
which relies on `rstatix` for some seemingly nice functions of this kind.
We could port over these functions to `psyntur` if necessary.

**Comment by lvjustice** [comment]
We could use the same code as `ezANOVA` if needs be, I just think we need to avoid loading another package to access the function

**Comment by mark-andrews** [comment]
Yes. I think then that we should incorporate these other functions into psyntur. We could have these functions directly accessible, or create wrappers if necessary. 

See also #20
