### ISSUE TITLE
Include a `labels` function in plots

### ISSUE THREAD

**Issue by lvjustice** [mark-andrews/psyntur#9]
Currently we need to load `tidyverse` to allow us to change axis labels. It would be good to have this as part of the graphing functions of psyntur so we don't need to load another package.

**Comment by mark-andrews** [comment]
Fair nuff.
Something like this
```r
tukeyboxplot(y = len, x = dose, xlab = 'foo', ylab = 'bar', data = ToothGrowth)
```
While we are at it, we probably should do axis limits too.
```r
tukeyboxplot(y = len, x = dose, xlim = c(-1, 5), ylab = c(10, 20, data = ToothGrowth)
```

**Comment by jensroes** [comment]
Sorry for the mess. I wanted to create a pull request for this issue (I've added labels and limits) but instead my last pull request appeared here. Patience with me :)
